version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nethd
    main: ./cmd/nethd
    binary: nethd
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: neth-cert
    main: ./cmd/neth-cert
    binary: neth-cert
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - dist/example.yaml
      - dist/nethd.service
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: rykth
    name: neth
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
