// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.4
// source: neth.proto

package nethpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LightHouseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//
	//	*LightHouseMessage_Query
	//	*LightHouseMessage_QueryReply
	//	*LightHouseMessage_Update
	//	*LightHouseMessage_WhoAmI
	//	*LightHouseMessage_WhoAmIReply
	//	*LightHouseMessage_Punch
	Body isLightHouseMessage_Body `protobuf_oneof:"body"`
}

func (x *LightHouseMessage) Reset() {
	*x = LightHouseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightHouseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightHouseMessage) ProtoMessage() {}

func (x *LightHouseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightHouseMessage.ProtoReflect.Descriptor instead.
func (*LightHouseMessage) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{0}
}

func (m *LightHouseMessage) GetBody() isLightHouseMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *LightHouseMessage) GetQuery() *HostQuery {
	if x, ok := x.GetBody().(*LightHouseMessage_Query); ok {
		return x.Query
	}
	return nil
}

func (x *LightHouseMessage) GetQueryReply() *HostQueryReply {
	if x, ok := x.GetBody().(*LightHouseMessage_QueryReply); ok {
		return x.QueryReply
	}
	return nil
}

func (x *LightHouseMessage) GetUpdate() *HostUpdateNotification {
	if x, ok := x.GetBody().(*LightHouseMessage_Update); ok {
		return x.Update
	}
	return nil
}

func (x *LightHouseMessage) GetWhoAmI() *WhoAmI {
	if x, ok := x.GetBody().(*LightHouseMessage_WhoAmI); ok {
		return x.WhoAmI
	}
	return nil
}

func (x *LightHouseMessage) GetWhoAmIReply() *WhoAmIReply {
	if x, ok := x.GetBody().(*LightHouseMessage_WhoAmIReply); ok {
		return x.WhoAmIReply
	}
	return nil
}

func (x *LightHouseMessage) GetPunch() *HostPunchNotification {
	if x, ok := x.GetBody().(*LightHouseMessage_Punch); ok {
		return x.Punch
	}
	return nil
}

type isLightHouseMessage_Body interface {
	isLightHouseMessage_Body()
}

type LightHouseMessage_Query struct {
	Query *HostQuery `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type LightHouseMessage_QueryReply struct {
	QueryReply *HostQueryReply `protobuf:"bytes,2,opt,name=query_reply,json=queryReply,proto3,oneof"`
}

type LightHouseMessage_Update struct {
	Update *HostUpdateNotification `protobuf:"bytes,3,opt,name=update,proto3,oneof"`
}

type LightHouseMessage_WhoAmI struct {
	WhoAmI *WhoAmI `protobuf:"bytes,4,opt,name=who_am_i,json=whoAmI,proto3,oneof"`
}

type LightHouseMessage_WhoAmIReply struct {
	WhoAmIReply *WhoAmIReply `protobuf:"bytes,5,opt,name=who_am_i_reply,json=whoAmIReply,proto3,oneof"`
}

type LightHouseMessage_Punch struct {
	Punch *HostPunchNotification `protobuf:"bytes,6,opt,name=punch,proto3,oneof"`
}

func (*LightHouseMessage_Query) isLightHouseMessage_Body() {}

func (*LightHouseMessage_QueryReply) isLightHouseMessage_Body() {}

func (*LightHouseMessage_Update) isLightHouseMessage_Body() {}

func (*LightHouseMessage_WhoAmI) isLightHouseMessage_Body() {}

func (*LightHouseMessage_WhoAmIReply) isLightHouseMessage_Body() {}

func (*LightHouseMessage_Punch) isLightHouseMessage_Body() {}

// HostQuery asks a lighthouse for the known real addresses of a VPN peer.
type HostQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpnIp string `protobuf:"bytes,1,opt,name=vpn_ip,json=vpnIp,proto3" json:"vpn_ip,omitempty"` // e.g. "10.0.0.2"
}

func (x *HostQuery) Reset() {
	*x = HostQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostQuery) ProtoMessage() {}

func (x *HostQuery) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostQuery.ProtoReflect.Descriptor instead.
func (*HostQuery) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{1}
}

func (x *HostQuery) GetVpnIp() string {
	if x != nil {
		return x.VpnIp
	}
	return ""
}

// HostQueryReply carries the real UDP addresses known for a VPN peer.
// addrs may be empty if the lighthouse has no record of the peer.
type HostQueryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpnIp string    `protobuf:"bytes,1,opt,name=vpn_ip,json=vpnIp,proto3" json:"vpn_ip,omitempty"`
	Addrs []*IpPort `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *HostQueryReply) Reset() {
	*x = HostQueryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostQueryReply) ProtoMessage() {}

func (x *HostQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostQueryReply.ProtoReflect.Descriptor instead.
func (*HostQueryReply) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{2}
}

func (x *HostQueryReply) GetVpnIp() string {
	if x != nil {
		return x.VpnIp
	}
	return ""
}

func (x *HostQueryReply) GetAddrs() []*IpPort {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// HostUpdateNotification is sent by a node to lighthouses to advertise its
// current real UDP addresses. Sent once at startup and periodically thereafter.
type HostUpdateNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs []*IpPort `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *HostUpdateNotification) Reset() {
	*x = HostUpdateNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostUpdateNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostUpdateNotification) ProtoMessage() {}

func (x *HostUpdateNotification) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostUpdateNotification.ProtoReflect.Descriptor instead.
func (*HostUpdateNotification) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{3}
}

func (x *HostUpdateNotification) GetAddrs() []*IpPort {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// WhoAmI asks the lighthouse to reflect the sender's real UDP address back.
// Used to discover the sender's external IP/port behind NAT.
type WhoAmI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhoAmI) Reset() {
	*x = WhoAmI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoAmI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmI) ProtoMessage() {}

func (x *WhoAmI) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmI.ProtoReflect.Descriptor instead.
func (*WhoAmI) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{4}
}

// WhoAmIReply carries the sender's observed (external) address.
type WhoAmIReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr *IpPort `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *WhoAmIReply) Reset() {
	*x = WhoAmIReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoAmIReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIReply) ProtoMessage() {}

func (x *WhoAmIReply) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIReply.ProtoReflect.Descriptor instead.
func (*WhoAmIReply) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{5}
}

func (x *WhoAmIReply) GetAddr() *IpPort {
	if x != nil {
		return x.Addr
	}
	return nil
}

// HostPunchNotification is sent by a lighthouse to a node, instructing it to
// send UDP packets to the listed addresses in order to punch a NAT hole.
type HostPunchNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpnIp string    `protobuf:"bytes,1,opt,name=vpn_ip,json=vpnIp,proto3" json:"vpn_ip,omitempty"` // VPN IP of the peer to punch toward
	Addrs []*IpPort `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`              // real addresses to punch
}

func (x *HostPunchNotification) Reset() {
	*x = HostPunchNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostPunchNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPunchNotification) ProtoMessage() {}

func (x *HostPunchNotification) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPunchNotification.ProtoReflect.Descriptor instead.
func (*HostPunchNotification) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{6}
}

func (x *HostPunchNotification) GetVpnIp() string {
	if x != nil {
		return x.VpnIp
	}
	return ""
}

func (x *HostPunchNotification) GetAddrs() []*IpPort {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// IpPort is a UDP endpoint (IPv4 or IPv6 address + port).
type IpPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // dotted-decimal IPv4 or colon-hex IPv6
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // 1–65535
}

func (x *IpPort) Reset() {
	*x = IpPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpPort) ProtoMessage() {}

func (x *IpPort) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpPort.ProtoReflect.Descriptor instead.
func (*IpPort) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{7}
}

func (x *IpPort) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IpPort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// HandshakeDetails is serialised separately, signed with HMAC, and carried
// inside HandshakeMessage.details. It binds the Noise session to the neth
// certificate identity and provides a replay anchor via the timestamp.
type HandshakeDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert           []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`                                            // PEM-encoded neth certificate of the sender
	InitiatorIndex uint32 `protobuf:"varint,2,opt,name=initiator_index,json=initiatorIndex,proto3" json:"initiator_index,omitempty"` // connection index chosen by the initiator
	ResponderIndex uint32 `protobuf:"varint,3,opt,name=responder_index,json=responderIndex,proto3" json:"responder_index,omitempty"` // connection index chosen by the responder (stage 1 only)
	Time           uint64 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`                                           // Unix timestamp (nanoseconds) — limits replay window
}

func (x *HandshakeDetails) Reset() {
	*x = HandshakeDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeDetails) ProtoMessage() {}

func (x *HandshakeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeDetails.ProtoReflect.Descriptor instead.
func (*HandshakeDetails) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{8}
}

func (x *HandshakeDetails) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *HandshakeDetails) GetInitiatorIndex() uint32 {
	if x != nil {
		return x.InitiatorIndex
	}
	return 0
}

func (x *HandshakeDetails) GetResponderIndex() uint32 {
	if x != nil {
		return x.ResponderIndex
	}
	return 0
}

func (x *HandshakeDetails) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// HandshakeMessage is the complete handshake packet body.
//
//	details       — serialised HandshakeDetails (plaintext, covered by hmac)
//	noise_payload — the raw Noise handshake message bytes produced by flynn/noise
//	hmac          — HMAC-SHA256(key=sender_cert_fingerprint, data=details||noise_payload)
//
// The HMAC lets the receiver cheaply authenticate the sender's certificate
// before performing the more expensive Noise ReadMessage operation.
type HandshakeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details      []byte `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	NoisePayload []byte `protobuf:"bytes,2,opt,name=noise_payload,json=noisePayload,proto3" json:"noise_payload,omitempty"`
	Hmac         []byte `protobuf:"bytes,3,opt,name=hmac,proto3" json:"hmac,omitempty"`
}

func (x *HandshakeMessage) Reset() {
	*x = HandshakeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeMessage) ProtoMessage() {}

func (x *HandshakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_neth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeMessage.ProtoReflect.Descriptor instead.
func (*HandshakeMessage) Descriptor() ([]byte, []int) {
	return file_neth_proto_rawDescGZIP(), []int{9}
}

func (x *HandshakeMessage) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HandshakeMessage) GetNoisePayload() []byte {
	if x != nil {
		return x.NoisePayload
	}
	return nil
}

func (x *HandshakeMessage) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

var File_neth_proto protoreflect.FileDescriptor

var file_neth_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x65,
	0x74, 0x68, 0x22, 0xce, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6e, 0x65, 0x74, 0x68, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x37, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x68, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0a,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x65, 0x74,
	0x68, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x77, 0x68, 0x6f, 0x5f, 0x61, 0x6d, 0x5f, 0x69, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6e, 0x65, 0x74, 0x68, 0x2e, 0x57, 0x68, 0x6f, 0x41,
	0x6d, 0x49, 0x48, 0x00, 0x52, 0x06, 0x77, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x12, 0x38, 0x0a, 0x0e,
	0x77, 0x68, 0x6f, 0x5f, 0x61, 0x6d, 0x5f, 0x69, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x74, 0x68, 0x2e, 0x57, 0x68, 0x6f, 0x41,
	0x6d, 0x49, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x77, 0x68, 0x6f, 0x41, 0x6d,
	0x49, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x05, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x74, 0x68, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x42, 0x06, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a, 0x09, 0x48, 0x6f, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x6e, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x70, 0x6e, 0x49, 0x70, 0x22, 0x4b, 0x0a, 0x0e, 0x48, 0x6f, 0x73, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x6e,
	0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x70, 0x6e, 0x49, 0x70,
	0x12, 0x22, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6e, 0x65, 0x74, 0x68, 0x2e, 0x49, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x61,
	0x64, 0x64, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x16, 0x48, 0x6f, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22,
	0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6e, 0x65, 0x74, 0x68, 0x2e, 0x49, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x61, 0x64, 0x64,
	0x72, 0x73, 0x22, 0x08, 0x0a, 0x06, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x22, 0x2f, 0x0a, 0x0b,
	0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6e, 0x65, 0x74, 0x68,
	0x2e, 0x49, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x52, 0x0a,
	0x15, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x6e, 0x5f, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x70, 0x6e, 0x49, 0x70, 0x12, 0x22, 0x0a,
	0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6e,
	0x65, 0x74, 0x68, 0x2e, 0x49, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72,
	0x73, 0x22, 0x2c, 0x0a, 0x06, 0x49, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x8c, 0x01, 0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x65,
	0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x6e, 0x6f, 0x69, 0x73, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6e, 0x6f, 0x69, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6d, 0x61, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x68, 0x6d, 0x61, 0x63, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x79, 0x6b, 0x74, 0x68, 0x2f, 0x6e, 0x65, 0x74, 0x68, 0x2f, 0x6e,
	0x65, 0x74, 0x68, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_neth_proto_rawDescOnce sync.Once
	file_neth_proto_rawDescData = file_neth_proto_rawDesc
)

func file_neth_proto_rawDescGZIP() []byte {
	file_neth_proto_rawDescOnce.Do(func() {
		file_neth_proto_rawDescData = protoimpl.X.CompressGZIP(file_neth_proto_rawDescData)
	})
	return file_neth_proto_rawDescData
}

var file_neth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_neth_proto_goTypes = []interface{}{
	(*LightHouseMessage)(nil),      // 0: neth.LightHouseMessage
	(*HostQuery)(nil),              // 1: neth.HostQuery
	(*HostQueryReply)(nil),         // 2: neth.HostQueryReply
	(*HostUpdateNotification)(nil), // 3: neth.HostUpdateNotification
	(*WhoAmI)(nil),                 // 4: neth.WhoAmI
	(*WhoAmIReply)(nil),            // 5: neth.WhoAmIReply
	(*HostPunchNotification)(nil),  // 6: neth.HostPunchNotification
	(*IpPort)(nil),                 // 7: neth.IpPort
	(*HandshakeDetails)(nil),       // 8: neth.HandshakeDetails
	(*HandshakeMessage)(nil),       // 9: neth.HandshakeMessage
}
var file_neth_proto_depIdxs = []int32{
	1,  // 0: neth.LightHouseMessage.query:type_name -> neth.HostQuery
	2,  // 1: neth.LightHouseMessage.query_reply:type_name -> neth.HostQueryReply
	3,  // 2: neth.LightHouseMessage.update:type_name -> neth.HostUpdateNotification
	4,  // 3: neth.LightHouseMessage.who_am_i:type_name -> neth.WhoAmI
	5,  // 4: neth.LightHouseMessage.who_am_i_reply:type_name -> neth.WhoAmIReply
	6,  // 5: neth.LightHouseMessage.punch:type_name -> neth.HostPunchNotification
	7,  // 6: neth.HostQueryReply.addrs:type_name -> neth.IpPort
	7,  // 7: neth.HostUpdateNotification.addrs:type_name -> neth.IpPort
	7,  // 8: neth.WhoAmIReply.addr:type_name -> neth.IpPort
	7,  // 9: neth.HostPunchNotification.addrs:type_name -> neth.IpPort
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_neth_proto_init() }
func file_neth_proto_init() {
	if File_neth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_neth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightHouseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostQueryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostUpdateNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoAmI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoAmIReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostPunchNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neth_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_neth_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LightHouseMessage_Query)(nil),
		(*LightHouseMessage_QueryReply)(nil),
		(*LightHouseMessage_Update)(nil),
		(*LightHouseMessage_WhoAmI)(nil),
		(*LightHouseMessage_WhoAmIReply)(nil),
		(*LightHouseMessage_Punch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neth_proto_goTypes,
		DependencyIndexes: file_neth_proto_depIdxs,
		MessageInfos:      file_neth_proto_msgTypes,
	}.Build()
	File_neth_proto = out.File
	file_neth_proto_rawDesc = nil
	file_neth_proto_goTypes = nil
	file_neth_proto_depIdxs = nil
}
